apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql57-database-operator
rules:
- apiGroups: ["k8s.networkteam.com"]
  resources: ["mysql57databases"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets", "services"]
  verbs: ["create", "get", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mysql57-database-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql57-database-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${KUBE_NAMESPACE}